### PR TITLE
Change isUpdating guard to assertionFailure instead of silently dropping events

### PR DESCRIPTION
**Pull request by CyExy**
This is just a little debugging aid, it took me a while to realize that some of the events are dropped, saying that https://github.com/ReactiveKit/ReactiveKit/commit/1fae49b15bc46137334f9d44f217afbd909ecc3a wasn't adding tests so not sure is it safe to merge

### CODE REVIEW

**Comment by srdanrasic** [comment]
Hi @CyExy, there is one problem with this. Guard is being hit on bidirectional bindings and in that case it's valid and necessary to drop the event. 

```swift
let a = Property(0)
let b = Property(0)

a.bindTo(b)
b.bindTo(a)

a.value = 3 // a updates b to 3, b tries to update a to 3, but since a's isUpdating==true, it breaks the infinite recursion
```

I'm not sure if it's possible to solve bidirectional binding in any other way.

**Comment by frankschlegel** [comment]
@srdanrasic: Maybe you can pass some kind of token with an event that somehow identifies the "cause" of the event. And if an incoming event carries the token you just used to send one you can ignore it.

Just thinking out loud here…

Btw, I also ran into an issue with the `isUpdating` flag when updating values concurrently in close succession. The problem was that newer values were dropped because the property was still updating the previous value.

**Comment by srdanrasic** [comment]
Passing the token around would involve changing base Event type and I don't want to do that just for this feature. I appreciate thinking aloud anyway :)

Thinking further, it might be possible to move `isUpdating` flag into the binding itself, into the observeNext closure of binding. Let me experiment with that.

**Comment by CyExy** [comment]
moving it to the `observeNext` sounds promising

**Pull request closed without merging**
