### PR TITLE
Align some APIs with Combine

### PR DESCRIPTION
**Pull request by srdanrasic**
I'm starting work on aligning some API's with those of Combine. Thinking of doing this in batches and releasing small batches rather than one huge change. What do you think @tonyarnold ?

### CODE REVIEW

**Comment by tonyarnold** [comment]
This is excellent, and exactly what I was thinking when I messaged you the other day. Thank you!

**Review by tonyarnold — APPROVED** [review]
🎉 You may wish to amend some of the commit messages - seems like there are words missing.

**Comment by tonyarnold** [comment]
Also, if you want to make a Hitlist of things that need to be done, I'm happy to pitch in as I can.

**Comment by srdanrasic** [comment]
Thanks @tonyarnold. I'll make a release from this and then do some other changes. I'd like to rename Observer to Subscriber, but that's going to be a bit tricky. I want to do everything in a backward compatible way.

**Comment by tonyarnold** [comment]
Can you mark a type alias as deprecated?

**Comment by srdanrasic** [comment]
Yes, but there is also `observe` method that defines the `SignalProtocol` that should be renamed to `receive`. I think we could solve it by renaming `SignalProtocol` to something else, eg `_SignalProtocol`,  defining new `SignalProtocol` with the `receive` method that inherits from `_SignalProtocol` and then make an extension on `_SignalProtocol` that provides a default implementation of `observe` when `Self` is `SignalProtocol`... or something like that 😅

**Pull request merged**
