### PR TITLE
Complete zip() when any of its input signal completes.

### PR DESCRIPTION
**Pull request by jechol**
Fix for https://github.com/ReactiveKit/ReactiveKit/issues/139

### CODE REVIEW

**Comment by iandundas** [comment]
Many thanks! I should have fixed this myself

**Comment by jechol** [comment]
Nope, you gave me a good chance to contribute!

**Comment by jechol** [comment]
This has a bug. I'm fixing now... Please wait.

**Comment by jechol** [comment]
I'm now confident!

**Comment by srdanrasic** [comment]
Looking good @jechol! Thanks a lot :)

**Pull request merged**
