### PR TITLE
Update ReactiveKit.h

### PR DESCRIPTION
**Pull request by aixinlove**
in the same target.

### CODE REVIEW

**Comment by srdanrasic** [comment]
Hi @aixinlove, are you sure about this? Apple documentation says differently: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122

Am I missing something?

**Comment by aixinlove** [comment]
@srdanrasic use <framework name/header.h> in client app. but "header.h" in your framework.
i use pod to install "ReactiveKit", it fail on this. when apply my request. its ok.

**Comment by srdanrasic** [comment]
Hmm, I'm still puzzled why this is happening. Apple documentation explicitly says to use "ModuleName/ModuleName.h" syntax.

Also, I'm using this pod in other projects, eg [ReactiveGitter](ReactiveKit/ReactiveGitter), and not experiencing the issue. 

Do you have latest CocoaPods?

**Comment by aixinlove** [comment]
@srdanrasic  thanks, i fix it when update CocoaPods.

**Comment by srdanrasic** [comment]
Ah, glad to hear that :)

**Pull request closed without merging**
